on:
  push:
    branches:
      -master
name: Publish Website to Cpanel
jobs:
  web-deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Get latest code
      uses: actions/checkout@v2
    - name: Sync Files
      uses: SamKirkland/FTP-Deploy-Action@4.3.0
      with:
        ftp:server: ${{ secrets.FTP_SERVER }}
        ftp-username: ${{ secrets.FTP_USERNAME }}
        ftp-password: ${{ secrets.FTP_PASSWORD }}
  
